build: ../python/djvuedlib/hiddentext/djvused_hiddentext_parser.py 

../python/djvuedlib/hiddentext/djvused_hiddentext_parser.py : djvused_hiddentext.ebnf
	grako -o ../python/djvuedlib/hiddentext/djvused_hiddentext_parser.py -m djvused_hiddentext djvused_hiddentext.ebnf
